### ISSUE TITLE
Remove the dependency to metrics lib

### ISSUE THREAD

**Issue by comcastrong** [sethfitz/metricsd#9]
Hey, mojodna,
  Sorry to put this in the issue list. If you have a maillist, please let know. I will move it.
  Is it possible to remove the dependency to metrics lib? Based on the reading from here http://readthedocs.org/docs/graphite/en/latest/feeding-carbon.html. It should be very straight forward to write to carbon directly and we can choose different protocol: plaintext, pickle or even AMQP. Can you please explain to me what's the benefits you use metrics lib here?
  Thank you.
  Yongjun Rong

**Comment by sethfitz** [comment]
Math.  Flushing to carbon (via `GraphiteReporter`; it uses the plaintext method).  `metricsd` does very little itself since @codahale was kind enough to implement all sorts of statistical methods in the metrics library.  All this does is provide a UDP interface to `metrics` and configures it to use Graphite.

If you're looking for something simpler (but with fewer features, since it only implements a subset of the math), check out etsy/statsd.

**Comment by comcastrong** [comment]
Thank you. Can you explain a little bit more what math functions the metrics lib provided?

**Comment by sethfitz** [comment]
http://codahale.com/codeconf-2011-04-09-metrics-metrics-everywhere.pdf
